# Generated PySpark code from SAS migration
# Execution order optimized by ExecutionOrderOptimizer

import numpy as np
import os
import pandas as pd
from pyspark.sql import SparkSession
from pyspark.sql.functions import abs as ps_abs, col, lit

spark = SparkSession.builder.appName("SAS_Migration").getOrCreate()
spark = SparkSession.builder.appName('Treynor_Ratio_test1').getOrCreate()

# Generated PySpark code from SAS migration
# Generated by Graph-Based Migration Tool

# Calculate discrete returns using pandas

# Calculate Treynor Ratio using pandas/numpy
# Assume 'SPY' is the benchmark column, risk-free rate Rf=0.01/252, scale=252

rf = 0.01 / 252

bm_returns = returns_pd['SPY'] - rf

bm_var = bm_returns.var()

treynor_ratios = {}
for col_name in ['IBM', 'GE', 'DOW', 'GOOGL']:

# Initialize Spark session

treynor_ratio_df = pd.DataFrame([treynor_ratios])
treynor_ratio_df['SPY'] = np.nan

# Convert pandas DataFrames to Spark DataFrames

TreynorRatio = spark.createDataFrame(treynor_ratio_df)

# If tables have 0 records, delete them (drop DataFrames)
if TreynorRatio.count() == 0:

    returns_from_r = None

# If TreynorRatio does not exist, create error row
if TreynorRatio is None:

    error_data = [{'date': -1, 'IBM': -999, 'GE': -999, 'DOW': -999, 'GOOGL': -999, 'SPY': -999}]

    TreynorRatio = spark.createDataFrame(error_data)

    error_data = [{'date': 1, 'IBM': 999, 'GE': 999, 'DOW': 999, 'GOOGL': 999, 'SPY': 999}]

    returns_from_r = spark.createDataFrame(error_data)

# Compare DataFrames: absolute difference for IBM, GE, DOW, GOOGL > 1e-5

    pass_var = True

# Import necessary libraries

    notes = 'Passed'
    print('NOTE: NO ERROR IN TEST Treynor_Ratio_TEST1')
else:

    pass_var = False

    notes = 'Differences detected in outputs.'
    print('ERROR: PROBLEM IN TEST Treynor_Ratio_TEST1')

# Set up Spark session

# Load prices.csv as Spark DataFrame

prices_path = os.path.join(dir, 'prices.csv')

prices_pd = pd.read_csv(prices_path)
prices_pd['date'] = pd.to_datetime(prices_pd['date'])
prices_pd.set_index('date', inplace=True)

returns_pd = prices_pd.pct_change().dropna()

excess_returns = returns_pd.sub(rf)

cov_matrix = excess_returns.cov()

    beta = cov_matrix.loc[col_name, 'SPY'] / bm_var if bm_var != 0 else np.nan
    treynor_ratios[col_name] = (excess_returns[col_name].mean() * 252) / beta if beta != 0 else np.nan

returns_from_r = spark.createDataFrame(returns_pd.reset_index())

    TreynorRatio = None
if returns_from_r.count() == 0:

# If returns_from_r does not exist, create error row
if returns_from_r is None:

diff = returns_from_r.join(TreynorRatio, how='inner', on=None, lsuffix='_r', rsuffix='_t') \
    .select(
        col('date'),
        (col('IBM') - TreynorRatio['IBM']).alias('IBM_diff'),
        (col('GE') - TreynorRatio['GE']).alias('GE_diff'),
        (col('DOW') - TreynorRatio['DOW']).alias('DOW_diff'),
        (col('GOOGL') - TreynorRatio['GOOGL']).alias('GOOGL_diff')
    )

diff_filtered = diff.filter(
    (ps_abs(col('IBM_diff')) > 1e-5) |
    (ps_abs(col('GE_diff')) > 1e-5) |
    (ps_abs(col('DOW_diff')) > 1e-5) |
    (ps_abs(col('GOOGL_diff')) > 1e-5)
)

n = diff_filtered.count()

# Set pass/notes variables based on comparison
if n == 0:

# If keep is False, delete intermediate DataFrames
if not keep:
    del diff, returns_from_r, TreynorRatio

# Macro variables (should be set externally or passed as arguments)
# n, dir, nv, keep
# Example: dir = '/path/to/dir', keep = False
