#!/usr/bin/env python3
"""
Python Package Generator for SAS to PySpark Migration

This module generates proper Python package structure for migrated PySpark code,
including setup.py, requirements.txt, __init__.py files, and README.md.
"""

import os
from pathlib import Path
from typing import List, Dict, Optional
from datetime import datetime


class PackageGenerator:
    """Generates Python package structure for migrated code"""

    def __init__(self, package_name: str = "sas_migration", version: str = "0.1.0"):
        """
        Initialize package generator

        Args:
            package_name: Name of the Python package
            version: Package version
        """
        self.package_name = package_name
        self.version = version

    def generate_setup_py(self, output_root: str, package_dirs: List[str]) -> str:
        """
        Generate setup.py file

        Args:
            output_root: Root output directory
            package_dirs: List of package directories

        Returns:
            Path to created setup.py
        """
        # Get all packages (subdirectories with __init__.py)
        packages = [self.package_name]
        for pkg_dir in package_dirs:
            if pkg_dir != ".":
                pkg_path = pkg_dir.replace(os.sep, '.')
                packages.append(f"{self.package_name}.{pkg_path}")

        setup_content = f'''#!/usr/bin/env python3
"""
Setup configuration for {self.package_name}

Auto-generated by SAS to PySpark Migration Tool
Generated on: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
"""

from setuptools import setup, find_packages

setup(
    name="{self.package_name}",
    version="{self.version}",
    description="PySpark code migrated from SAS",
    author="SAS to PySpark Migration Tool",
    python_requires=">=3.8",
    packages=find_packages(),
    install_requires=[
        "pyspark>=3.0.0",
        "pandas>=1.0.0",
        "numpy>=1.18.0",
    ],
    extras_require={{
        "dev": [
            "pytest>=6.0.0",
            "pytest-cov>=2.0.0",
            "black>=21.0",
            "flake8>=3.9.0",
        ]
    }},
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
    ],
)
'''

        setup_path = Path(output_root) / "setup.py"
        setup_path.write_text(setup_content)
        return str(setup_path)

    def generate_requirements_txt(self, output_root: str) -> str:
        """
        Generate requirements.txt file

        Args:
            output_root: Root output directory

        Returns:
            Path to created requirements.txt
        """
        requirements = [
            "# Python requirements for migrated PySpark code",
            f"# Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
            "",
            "# Core PySpark dependencies",
            "pyspark>=3.0.0",
            "",
            "# Data processing",
            "pandas>=1.0.0",
            "numpy>=1.18.0",
            "",
            "# Optional: Additional utilities",
            "python-dateutil>=2.8.0",
            "",
            "# Development dependencies (optional)",
            "# pytest>=6.0.0",
            "# black>=21.0",
            "# flake8>=3.9.0",
        ]

        req_path = Path(output_root) / "requirements.txt"
        req_path.write_text("\n".join(requirements))
        return str(req_path)

    def generate_init_py(self, directory: str, module_description: Optional[str] = None) -> str:
        """
        Generate __init__.py file for a package directory

        Args:
            directory: Directory path
            module_description: Optional description for the module

        Returns:
            Path to created __init__.py
        """
        # Determine module name from directory
        dir_name = Path(directory).name if Path(directory).name != self.package_name else self.package_name

        if module_description is None:
            # Auto-generate description based on directory name
            module_description = f"PySpark code for {dir_name.replace('_', ' ')}"

        init_content = f'''"""
{module_description}

Auto-generated by SAS to PySpark Migration Tool
"""

__version__ = "{self.version}"
'''

        init_path = Path(directory) / "__init__.py"
        init_path.write_text(init_content)
        return str(init_path)

    def generate_readme_md(
        self,
        output_root: str,
        file_count: int,
        package_dirs: List[str],
        migration_summary: Optional[Dict] = None
    ) -> str:
        """
        Generate README.md file

        Args:
            output_root: Root output directory
            file_count: Number of migrated files
            package_dirs: List of package directories
            migration_summary: Optional migration summary stats

        Returns:
            Path to created README.md
        """
        readme_lines = [
            f"# {self.package_name}",
            "",
            "PySpark code migrated from SAS using automated migration tool.",
            "",
            f"**Generated on:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
            f"**Total files migrated:** {file_count}",
            "",
            "## Project Structure",
            "",
            "```",
        ]

        # Add directory tree
        readme_lines.append(f"{self.package_name}/")
        for pkg_dir in sorted(package_dirs):
            if pkg_dir != ".":
                depth = pkg_dir.count(os.sep)
                indent = "  " * (depth + 1)
                dir_name = Path(pkg_dir).name
                readme_lines.append(f"{indent}├── {dir_name}/")

        readme_lines.extend([
            "```",
            "",
            "## Installation",
            "",
            "### Using pip",
            "",
            "```bash",
            "# Install package",
            "pip install -e .",
            "",
            "# Install with development dependencies",
            "pip install -e \".[dev]\"",
            "```",
            "",
            "### Using requirements.txt",
            "",
            "```bash",
            "pip install -r requirements.txt",
            "```",
            "",
            "## Usage",
            "",
            "### Running PySpark Jobs",
            "",
            "```python",
            "from pyspark.sql import SparkSession",
            f"from {self.package_name} import *",
            "",
            "# Create Spark session",
            "spark = SparkSession.builder \\",
            "    .appName(\"Migrated SAS Job\") \\",
            "    .getOrCreate()",
            "",
            "# Your migrated code here",
            "# ...",
            "```",
            "",
            "### Running from Command Line",
            "",
            "```bash",
            "# Submit PySpark job",
            "spark-submit your_migrated_script.py",
            "",
            "# With additional configuration",
            "spark-submit --master local[*] --driver-memory 4g your_migrated_script.py",
            "```",
            "",
            "## Migration Notes",
            "",
            "This code was automatically migrated from SAS. Please review the following:",
            "",
            "1. **Test thoroughly**: Automated migration may not capture all business logic nuances",
            "2. **Data types**: Verify that PySpark data types match your SAS data types",
            "3. **Performance**: PySpark may require optimization different from SAS",
            "4. **Dependencies**: Ensure all required data sources and libraries are available",
            "",
        ])

        if migration_summary:
            readme_lines.extend([
                "## Migration Summary",
                "",
            ])
            for key, value in migration_summary.items():
                readme_lines.append(f"- **{key}**: {value}")
            readme_lines.append("")

        readme_lines.extend([
            "## File Mappings",
            "",
            "Each migrated `.py` file has a corresponding `_mapping.txt` file that shows:",
            "- Original SAS code",
            "- Converted PySpark code",
            "- Explanation of the conversion",
            "",
            "Refer to these mapping files for detailed migration information.",
            "",
            "## Development",
            "",
            "### Code Formatting",
            "",
            "```bash",
            "# Format code with black",
            "black .",
            "",
            "# Lint with flake8",
            "flake8 .",
            "```",
            "",
            "### Testing",
            "",
            "```bash",
            "# Run tests",
            "pytest",
            "",
            "# With coverage",
            "pytest --cov",
            "```",
            "",
            "## Support",
            "",
            "For issues with the migration tool, please contact your development team.",
            "",
            "---",
            "",
            "*Auto-generated by SAS to PySpark Migration Tool*",
        ])

        readme_path = Path(output_root) / "README.md"
        readme_path.write_text("\n".join(readme_lines))
        return str(readme_path)

    def generate_gitignore(self, output_root: str) -> str:
        """
        Generate .gitignore file

        Args:
            output_root: Root output directory

        Returns:
            Path to created .gitignore
        """
        gitignore_content = '''# Python
__pycache__/
*.py[cod]
*$py.class
*.so
.Python
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
wheels/
*.egg-info/
.installed.cfg
*.egg

# Virtual environments
venv/
ENV/
env/

# IDEs
.vscode/
.idea/
*.swp
*.swo
*~

# PySpark
metastore_db/
derby.log
spark-warehouse/

# Logs
*.log

# OS
.DS_Store
Thumbs.db
'''

        gitignore_path = Path(output_root) / ".gitignore"
        gitignore_path.write_text(gitignore_content)
        return str(gitignore_path)

    def generate_full_package(
        self,
        output_root: str,
        package_dirs: List[str],
        file_count: int,
        migration_summary: Optional[Dict] = None
    ) -> Dict[str, str]:
        """
        Generate complete Python package structure

        Args:
            output_root: Root output directory
            package_dirs: List of package directories (relative paths)
            file_count: Number of migrated files
            migration_summary: Optional migration statistics

        Returns:
            Dictionary mapping file type to created file paths
        """
        created_files = {}

        # Create setup.py
        created_files['setup.py'] = self.generate_setup_py(output_root, package_dirs)

        # Create requirements.txt
        created_files['requirements.txt'] = self.generate_requirements_txt(output_root)

        # Create README.md
        created_files['README.md'] = self.generate_readme_md(
            output_root, file_count, package_dirs, migration_summary
        )

        # Create .gitignore
        created_files['.gitignore'] = self.generate_gitignore(output_root)

        # Create __init__.py in root
        created_files['__init__.py (root)'] = self.generate_init_py(
            output_root,
            f"{self.package_name} - Migrated PySpark code from SAS"
        )

        # Create __init__.py in all package directories
        for pkg_dir in package_dirs:
            if pkg_dir != ".":
                full_dir = Path(output_root) / pkg_dir
                if full_dir.exists():
                    init_file = self.generate_init_py(str(full_dir))
                    created_files[f'__init__.py ({pkg_dir})'] = init_file

        return created_files

    def create_package_directories(self, output_root: str, package_dirs: List[str]) -> List[str]:
        """
        Create all package directories if they don't exist

        Args:
            output_root: Root output directory
            package_dirs: List of relative directory paths

        Returns:
            List of created directory paths
        """
        created = []

        for pkg_dir in package_dirs:
            if pkg_dir != ".":
                full_path = Path(output_root) / pkg_dir
                if not full_path.exists():
                    full_path.mkdir(parents=True, exist_ok=True)
                    created.append(str(full_path))

        return created
